/*
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ProblemDetails;
import org.openapitools.client.model.Solicitud;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SolicitudApi
 */
@Disabled
class SolicitudApiTest {

    private final SolicitudApi api = new SolicitudApi();

    
    /**
     * 
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void solicitudComprobarSolicitudGetTest() {
        String nombreUsuario = null;
        Integer tok = null;

        List<Integer> response = api.solicitudComprobarSolicitudGet(nombreUsuario, tok);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void solicitudGetSolicitudesUsuarioGetTest() {
        String nombreUsuario = null;

        List<Integer> response = api.solicitudGetSolicitudesUsuarioGet(nombreUsuario);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void solicitudSolicitarPostTest() {
        String nombreUsuario = null;
        Solicitud solicitud = null;

        Object response = api.solicitudSolicitarPost(nombreUsuario, solicitud);

        // TODO: test validations
    }
    
}
